[project]
name = "typed-rest-example-webapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typed-rest[fastapi]>=0.1.0",
]
[tool.uv.sources]
typed-rest = { workspace = true }
